# Generated by Django 5.1.6 on 2025-04-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0033_rename_verification_status_teacher_verification_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_name', models.CharField(max_length=100)),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('study_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studyfield')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
        ),
    ]
