# Generated by Django 5.2 on 2025-05-01 14:12

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_teacher',
            name='lesson_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_teacher',
            name='teacher_delay',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_teacher',
            name='class_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
