# Generated by Django 5.2 on 2025-05-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_teacher_lesson_type_post_teacher_teacher_delay_and_more'),
        ('main', '0033_rename_verification_status_teacher_verification_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_teacher',
            name='department',
            field=models.ForeignKey(default='None-department', on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
    ]
