# Generated by Django 5.1.6 on 2025-05-11 01:10

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_teacher',
            name='created_at_jalali',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
