# Generated by Django 5.1.6 on 2025-05-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_teacher_created_at_jalali'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_teacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post_teacher',
            name='created_at_jalali',
        ),
    ]
