# Generated by Django 5.1.6 on 2025-05-11 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_teacher_created_at_and_more'),
        ('main', '0039_department_create_at_department_create_at_jalali_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_teacher',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
    ]
