# Generated by Django 5.1.6 on 2025-05-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_teacher_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_teacher',
            old_name='created_at',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='post_teacher',
            old_name='created_at_jalali',
            new_name='create_at_jalali',
        ),
    ]
