# Generated by Django 5.1.6 on 2025-02-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='name',
        ),
    ]
