# Generated by Django 5.1.6 on 2025-02-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_teacher_email_remove_teacher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
