# Generated by Django 5.1.6 on 2025-03-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='sms_code_sign_up',
            field=models.CharField(default='SMS', max_length=20),
        ),
    ]
