# Generated by Django 5.1.6 on 2025-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_teacher_sms_code_sign_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sms_code_sign_up',
            field=models.CharField(default='SMS', max_length=20),
        ),
    ]
