# Generated by Django 5.1.6 on 2025-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_student_sms_code_sign_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sms_code_sign_up',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
