# Generated by Django 5.1.6 on 2025-03-12 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_student_sms_code_sign_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sms_code_sign_up',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='sms_code_sign_up',
        ),
    ]
