# Generated by Django 5.1.6 on 2025-03-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_student_sms_code_sign_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
