# Generated by Django 5.1.6 on 2025-03-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
