# Generated by Django 5.1.6 on 2025-03-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(max_length=150),
        ),
    ]
