# Generated by Django 5.1.6 on 2025-03-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_student_field_of_study_alter_teacher_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_of_study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
