# Generated by Django 5.1.6 on 2025-03-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_student_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Field_of_study',
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
