# Generated by Django 5.1.6 on 2025-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_status_student_verification_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='verification_status',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
