# Generated by Django 5.1.6 on 2025-04-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_teacher_verification_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='status',
            new_name='teacher_status',
        ),
    ]
