# Generated by Django 5.1.6 on 2025-04-13 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_status_teacher_teacher_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_status',
            new_name='verification_teacher',
        ),
    ]
