# Generated by Django 5.1.6 on 2025-04-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_teacher_status_teacher_verification_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='verification_status',
            new_name='verification_phonenumber',
        ),
    ]
