# Generated by Django 5.1.6 on 2025-04-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_verification_status_student_verification_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='verification_status',
            new_name='verification_phonenumber',
        ),
    ]
