# Generated by Django 5.1.6 on 2025-05-03 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_rename_verification_status_teacher_verification_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='field_of_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.studyfield'),
        ),
    ]
