# Generated by Django 5.1.6 on 2025-05-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_department_create_at_department_create_at_jalali_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='create_at_jalali',
        ),
        migrations.RemoveField(
            model_name='student',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='create_at_jalali',
        ),
    ]
