# Generated by Django 5.1.6 on 2025-05-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_department_create_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyfield',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='studyfield',
            name='create_at_jalali',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='create_at_jalali',
        ),
    ]
