# Generated by Django 5.1.6 on 2025-05-17 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_educationlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.educationlevel'),
        ),
    ]
