# Generated by Django 5.1.6 on 2025-05-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_teacher_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.educationlevel'),
        ),
    ]
