# Generated by Django 5.1.6 on 2025-05-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_student_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
