# Generated by Django 5.1.6 on 2025-05-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_alter_teacher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True, help_text='آیا کاربر میتواند در سایت فعالیت کند یا خیر'),
        ),
    ]
